language: node_js
node_js:
  - "6"
  - "6.1"

  install:
    - npm install -g bower
    - npm install
    - bower install

# whitelist
branches:
  only:
    - master
    after_success: 'npm run coveralls'
# services: # enable various services
#   - mongodb     # will start mongodb



# script: npm start
