---
- hosts: staging
  user: azureuser
  tasks:
  - name: Removing previous war
    file: path=/home/azureuser/apache-tomcat-8.0.9/webapps/CustomerOnBoard-1.1.0-SNAPSHOT.war state=absent
  - name: Deploying war file
    copy: src=/var/lib/jenkins/jobs/CustomerOnBoard-StagingDeploy/workspace/target/ dest=/home/azureuser/apache-tomcat-8.0.9/webapps/
